server:
  port: 8762
  servlet:
    context-path: /v1
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
spring:
  application:
    name: gateway
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port:  ${RABBIT_MQ_PORT:5672}
    username: guest
    password: guest
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # =====================================
        - id: auth
          uri: lb://auth
          order: 8000
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
        - id: admin
          uri: lb://admin
          order: 8001
          predicates:
            - Path=/api/admin/**
          filters:
            - StripPrefix=2
    nacos:
      discovery:
        server-addr: localhost:8848 # Nacos服务接口(不能加http前缀)，直接访问localhost:8848/nacos可以进入管理页面


logging:
  level:
    com.loop.demo.gateway: info

#  Actuator 开放所有节点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
  endpoint:
    health:
      show-details: always
endpoints:
  health:
    sensitive: false



ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 500
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000000


gate:
  ignore:
    startWith: /auth/jwt