logging:
  level:
    tk.mybatis: debug
    com.loop.demo.admin: debug
spring:
  application:
    name: admin
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port:  ${RABBIT_MQ_PORT:5672}
    #    username: guest
    #    password: guest
    username: guest
    password: guest
    sleuth:
      enabled: true
      http:
        legacy:
          enabled: true
#  redis:
#    database: 2
#    host: ${REDIS_HOST:120.79.250.60}
#    password:
#    port: ${REDIS_PORT:6379}
#    pool:
#    max-active: 20
  datasource:
#    name: test
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/loop_admin_v2?useUnicode=true&characterEncoding=UTF8
#    url: jdbc:mysql://${MYSQL_HOST:120.79.250.60}:${MYSQL_PORT:3306}/loop_admin?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
    #阿里巴巴数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # Nacos服务接口(不能加http前缀)，直接访问localhost:8848/nacos可以进入管理页面
#  Actuator 开放所有节点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
  endpoint:
    health:
      show-details: always
endpoints:
  health:
    sensitive: false
mybatis:
  basepackage: com.loop.demo.admin.mapper
  xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: "classpath*:mapper/*.xml"

server:
  port: 9004



#不需要登录验证的地址
url:
  ignore:
    startWith: /jwt,/doc.html